---

- name: install openssh
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - openssh
    - mosh

- name: set ssh configuration
  template: src=templates/ssh_config.j2 dest=/etc/ssh/ssh_config owner=root group=root

- name: set sshd configuration
  template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root
  notify:
    - sshd restart

- name: Ensure that sshd is running
  service: name=sshd state=started enabled=yes

- name: create ssh firewall rules
  template: src=templates/1002-ssh.conf.j2 dest=/etc/ferm/ferm.d/1002-ssh.conf owner=root group=root
  notify:
    - ferm restart

- name: create mosh firewall rules
  template: src=templates/1004-mosh.conf.j2 dest=/etc/ferm/ferm.d/1004-mosh.conf owner=root group=root
  notify:
    - ferm restart

- name: create lastlog file
  file:
    path: /var/log/lastlog
    mode: 0644
    group: utmp
    state: file
